"""add symbol_aspect

Revision ID: 0d8de3527641
Revises: d677fcd39dc9
Create Date: 2023-08-01 15:14:41.125331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8de3527641'
down_revision = 'd677fcd39dc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('symbol_aspect', sa.String(), nullable=True))
    op.create_index(op.f('ix_predictions_symbol_aspect'), 'predictions', ['symbol_aspect'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_symbol_aspect'), table_name='predictions')
    op.drop_column('predictions', 'symbol_aspect')
    # ### end Alembic commands ###
